git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  autoFetch: false

keybinding:
  universal:
    # Assign <esc> to the return/quit action
    # The default 'q' might still work alongside this.
    quit: '<esc>'

os:
  editPreset: 'nvim-remote'
