[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["--login"]

[font]
size = 20

[font.bold]
family = "MonoLisa Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font Mono"
style = "Regular"

[window]
decorations = "none"
# dynamic_padding = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[font.offset]
x = 0
y = 1

[window.padding]
x = 0
y = 0

# [general]
# import = ["/Users/ruizhang/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
# LACKLUSTER COLORS
[colors.primary]
background = '#0A0A0A'

[colors.normal]
# black is gray0
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
# cyan is set to lack
cyan = '#708090' 
# white is set to luster
white = '#DEEEED'
