
[env]
TERM = "xterm-256color"

[font]
size = 20

[font.bold]
family = "MonoLisa Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font Mono"
style = "Regular"

[window]
decorations = "none"
dynamic_padding = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[general]
import = ["/Users/ruizhang/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
